const assert = require('node:assert/strict');
module.exports = async function ({ get, listeners, engine, nodes, body, windowEvents, setChat, game, setSave, commands, notices, extensionSettings }) {
    await listeners.init(); await listeners.init();
    const click = async id => { assert(get(id), id); assert(!get(id).disabled, id); return get(id).events.click(); };
    const enable = async () => { get('qhjt-game').checked = true; await get('qhjt-game').events.change(); };
    const command = value => commands.life.callback({}, value);
    const switchChat = async (id, data) => { setChat(id, data); await listeners.chat(); };
    assert(get('qhjt-host').hidden); assert.equal(get('qhjt-host').parentElement, body);
    for (const id of ['qhjt-add-user', 'qhjt-add-character', 'qhjt-control', 'qhjt-plus', 'qhjt-tab-actions', 'qhjt-actors']) assert(!get(id), id);
    for (const id of ['state', 'inventory', 'locations', 'npcs', 'settings']) assert(get('qhjt-tab-' + id));
    await enable(); assert(get('qhjt-overlay').open); assert(!get('qhjt-host').hidden);
    assert.equal(Object.keys(game().npcs).length, 0);
    await command('action add 摆摊'); await command('action add 摆摊'); assert.equal(Object.keys(game().actions).length, 1);
    await command('action list'); assert.equal(notices.at(-1), '摆摊');
    const dataA = { qingheji_tavern: game() };
    await switchChat('B', {}); assert(get('qhjt-host').hidden); await enable(); assert.equal(Object.keys(game().actions).length, 0);
    await switchChat('A', dataA); assert.equal(Object.keys(game().actions).length, 1);
    const input = async (id, name, extra = '') => {
        const promise = get(id).events.click(); get('qhjt-name').value = name; get('qhjt-name-extra').value = extra;
        get('qhjt-name-form').events.submit({ preventDefault() {} }); await promise;
    };
    await input('qhjt-add-inventory', '柴火', '5'); assert.equal(Object.values(game().inventory)[0].quantity, 5);
    await input('qhjt-add-inventory', '野菜'); assert.equal(Object.values(game().inventory)[1].quantityKnown, false);
    await input('qhjt-add-npc', '砚绒', '白发红眼'); assert.equal(Object.keys(game().npcs).length, 1);
    const npc = Object.values(game().npcs)[0]; assert(npc.known); await click('qhjt-npc-' + npc.id); assert(!get('qhjt-npc-detail').hidden);
    await input('qhjt-add-location', '后山', '简介'); assert.equal(Object.keys(game().locations).length, 1);
    const old = JSON.stringify(game()); setSave(async () => { throw Error('fail'); });
    await command('action add 应回滚'); assert.equal(JSON.stringify(game()), old); setSave(async () => {});
    await command('action remove 摆摊'); assert.equal(Object.keys(game().actions).length, 0);
    const isolated = { qingheji_tavern: game() }; await switchChat('C', {}); await enable();
    for (const field of ['locations', 'inventory', 'npcs', 'actions']) assert.equal(Object.keys(game()[field]).length, 0);
    await switchChat('A', isolated); assert.equal(Object.keys(game().inventory).length, 2);
    await click('qhjt-close'); assert(!get('qhjt-overlay').open);
    get('qhjt-master').checked = false; await get('qhjt-master').events.change(); assert(!get('qhjt-entry'));
    get('qhjt-master').checked = true; await get('qhjt-master').events.change();
    get('qhjt-host').remove(); await listeners.init();
    for (const id of ['qhjt-entry', 'qhjt-overlay', 'qhjt-panel']) assert.equal(nodes.filter(node => node.id === id && node.isConnected).length, 1);
    assert.equal(extensionSettings.qingheji_tavern.inventory, undefined);
    await switchChat(undefined, {}); assert(get('qhjt-game').disabled);
    console.log('PASS: simplified five-tab UI, no actor/User controls, manual inventory/NPC/location, chat isolation, action commands, rollback and floating lifecycle.');
};
